---
title: "File formats and APIs for spatial and spatiotemporal data"
author: "Edzer Pebesma"
date: "Jan 30, 2025"
output:
  html_document:
    toc: true
#    toc_float:
#      collapsed: false
#      smooth_scroll: false
#    toc_depth: 2
---

## Content

The workshop will first introduce the main spatial data models (vector: points/lines/polygons; raster: various grid types), their implementation in file formats and software libraries to read and write them. It will then introduce time series associated with such models (NetCDF, Zarr, CDL, CF conventions) and discuss APIs for retrieving satellite, weather and climate data.

### Vector data

```{r}
#| code-fold: true
library(sf)
library(dplyr) |> suppressPackageStartupMessages()
read_sf("https://github.com/r-spatial/sf/raw/main/inst/gpkg/nc.gpkg") |> 
		select(BIR74) |>
		plot(border = 'grey', pal = viridis::viridis(11))
```

### Raster data

### Time series

Typical data structure: table (e.g., a .csv) with a Date or DateTime column.

* Does time refer to a time instance, or to a time period? 
* Is the time period clear, and/or explicit (start- and end-time)?
* Are time stamps of a time "type", or in case of text, do time stamps follow a known schema such as [ISO8601](https://en.wikipedia.org/wiki/ISO_8601)?

### Data cubes

### Cloud-optimized geospatial, APIs
